// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/load': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/load').default>>>>
    }
    '/relay': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/relay').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
  }
}
export {}